### ISSUE TITLE
Incorrect icons and misalignment on update.

### ISSUE THREAD

**Issue by lech** [wyze/atom-seti-icons#54]
![seti_borken](https://cloud.githubusercontent.com/assets/396861/23490405/193e9d9c-febe-11e6-9f6c-e8e0d212a625.png)

The current update seems to have broken something. Updating the package has munged the icon layout and is presenting the wrong icons in so many wonderfully broken ways.

**Comment by Mine-MuYan** [comment]
Neither do I.
![image](https://cloud.githubusercontent.com/assets/23254569/23491024/bdf24582-ff36-11e6-9e89-a38fc6856745.png)
l think it  looks  uncomfortable.
Maybe you can add a new feature to control the horizontal alignment of icons,and users can customize the icon's horizontal alignment.
I hope my advice can be helpful.
Thanks.

**Comment by wyze** [comment]
Controlling the vertical alignment via setting would prove really difficult. As far as an easier fix, could you please list the theme you are using? When I reviewed it, they looked fine in the themes I have, but clearly not in your screenshots.

**Comment by brock-martin** [comment]
![tabs](https://cloud.githubusercontent.com/assets/20828425/23513992/ed182398-ff33-11e6-8262-627841d7201b.png)

I'm using One Dark (theme and syntax). Icons are all too high vertically in tabs and the tree view file listing. Thanks!

**Comment by wyze** [comment]
Maybe this is an issue on Windows? It looks fine to me on macOS. I would love if someone would be able to submit a PR with a fix.

**Comment by brock-martin** [comment]
I am on Windows, so that's possible but it only changed with the latest update. Thanks again!

**Comment by wadik12** [comment]
Maybe it's fault of changes with `horiz-adv-x` from 200 to 32 in seti.svg from my last PR? Someone with Windows can check this? 

I cannot check this, because I'm using OSX and Ubuntu, on both looks and works fine.

**Comment by wyze** [comment]
Also, this is definitely a change made upstream. You can see the issues reported https://github.com/jesseweed/seti-ui/issues/362 and https://github.com/jesseweed/seti-ui/issues/387.

I have an idea for a Windows only fix tonight that I will try out. If it proves successful, I can get a patch release out with the fix and submit the PR upstream to Seti UI to have the fix as well.

**Comment by brock-martin** [comment]
Great, thanks! I did edit that horiz-adv-x="32" setting to horiz-adv-x="200" in the svg file as a test. It's still off, but I'm not sure how to purge Atom's "cache" to make sure I'm seeing the change. Let me know if I can help test anything specific!

**Comment by saresq** [comment]
Is there any solution by this time?
im having the same issue

**Comment by wyze** [comment]
I just published [v1.4.1](https://github.com/wyze/atom-seti-icons/releases/tag/v1.4.1). Please give it a try and report back!

**Comment by brock-martin** [comment]
That did the trick, everything looks great in Windows with v1.4.1. Thanks!

**Comment by lech** [comment]
Thanks for the quick fix!

**Comment by ThomasMaitret** [comment]
I've updated but i still have the same issue, the icons are incorrectly aligned.
![capture](https://cloud.githubusercontent.com/assets/20746707/23544888/22e8e64a-fff9-11e6-831a-8a47c96635aa.PNG)

**Comment by wyze** [comment]
@ThomasMaitret, did you do a reload after updating, just in case? Also, what theme are you using?

**Comment by saresq** [comment]
Works like a charm!

I think there is something else to touch in the tab bar
![image](https://cloud.githubusercontent.com/assets/14084716/23552641/b1d756d2-fffb-11e6-8eea-79c30fcbcfa1.png)
But is far more usable and less anoying than prev. version hahah

thank you!!

**Comment by ThomasMaitret** [comment]
Yes I did a reload, but I still face the same issue. I use Atom material as UI theme and Oceanic Next as syntax theme.
